EXPERIMENT:
  NAME: ""
  TAG: "sdd_kd_AFPN,res32x4_sdd,shuv1_sdd"
  PROJECT: "SDD"
DATASET:
  TYPE: "cub200"

DISTILLER:
  TYPE: "SDD_KD"
  TEACHER: "resnet32x4_sdd"
  STUDENT: "ShuffleV1_afpn_sdd"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

