EXPERIMENT:
  NAME: ""
  TAG: "sdd_dkd_AFPN,wrn_40_2_sdd,mv2_sdd"
  PROJECT: "SDD"
DISTILLER:
  TYPE: "SDD_DKD"
  TEACHER: "wrn_40_2_sdd"
  STUDENT: "MobileNetV2_afpn_sdd"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 240
  LR: 0.04
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

DKD:
  BETA: 6.0