EXPERIMENT:
  NAME: ""
  TAG: "sdd_kd_AFPN,res34,res18"
  PROJECT: "SDD"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 10
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "SDD_KD"
  TEACHER: "ResNet34_sdd"
  STUDENT: "ResNet18_afpn_sdd"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 100
  LR: 0.1
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
DKD:
  CE_WEIGHT: 1.0
  BETA: 0.5
  T: 1.0
  WARMUP: 1
