EXPERIMENT:
  NAME: ""
  TAG: "sdd_kd_afpn,res50_sdd,vgg8_sdd"
  PROJECT: "SDD"
DISTILLER:
  TYPE: "SDD_KD"
  TEACHER: "ResNet50_sdd"
  STUDENT: "vgg8_afpn_sdd"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 240
  LR: 0.2
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
